export const tableProperties = {
    "tableProperties": {
        "TBL_ID": 1,
        "TBL_DB_NAME": "USERS",
        "TBL_LABEL": "Users",
        "TBL_QUERY_ID": 1,
        "TBL_CTX_ID": [
            {
                "ROW_ID": 1,
                "LNG_ID": "en",
                "CTX_ID": 1,
                "VAL_ID": 1,
                "VAL_SEQ": 1,
                "VAL_LABEL": "Display Roles",
                "VAL_COMPONENT": "FormsTable",
                "VAL_COMPONENT_ID": 3,
                "DYNAMIC_PARAMS": "RLU_APPS_ID=USR_APPS_ID;RLU_USER_ID=USR_ID",
                "FIXED_PARAMS": null,
                "POOL_PARAMS": null
            },
        ],
        "TBL_EDITABLE": true,
        "TBL_UPLOADABLE": true,
        "TBL_TREE_ID": null,
        "TBL_FRM_ID": null,
        "FRM_LABEL": "Security - Users",
        "TBL_KEY": [
            "USR_APPS_ID",
            "USR_ID"
        ],
        "TBL_AUDIT": false,
        "TBL_BURST": false,
        "TBL_WORKBOOK": null,
        "TBL_SHEET": null,
        "TBL_AUTO_LOAD": true
    },
    "filters": {
        "items": [
            {
                "ROW_ID": 1,
                "LNG_ID": "en",
                "TBL_ID": 1,
                "COL_ID": 1,
                "COL_SEQ": 1,
                "COL_DD_ID": "APPS_ID",
                "COL_LABEL": "Application ID",
                "COL_TARGET": "USR_APPS_ID",
                "COL_TYPE": "number",
                "COL_RULES": "LOOKUP",
                "COL_RULES_VALUES": "1",
                "COL_DEFAULT": null,
                "COL_VISIBLE": "Y",
                "COL_DISABLED": "N",
                "COL_REQUIRED": "Y",
                "COL_KEY": "Y",
                "COL_FILTER": "N",
                "DYNAMIC_PARAMS": null,
                "FIXED_PARAMS": null,
                "POOL_PARAMS": null,
                "OUTPUT_PARAMS": null,
                "COL_CDN_ID": null,
                "CDN_DYNAMIC_PARAMS": null,
                "CDN_FIXED_PARAMS": null
            },
            {
                "ROW_ID": 2,
                "LNG_ID": "en",
                "TBL_ID": 1,
                "COL_ID": 3,
                "COL_SEQ": 3,
                "COL_DD_ID": "USR_ID",
                "COL_LABEL": "User ID",
                "COL_TARGET": "USR_ID",
                "COL_TYPE": "text",
                "COL_RULES": "DISABLED",
                "COL_RULES_VALUES": "6",
                "COL_DEFAULT": null,
                "COL_VISIBLE": "Y",
                "COL_DISABLED": "N",
                "COL_REQUIRED": "Y",
                "COL_KEY": "Y",
                "COL_FILTER": "Y",
                "DYNAMIC_PARAMS": null,
                "FIXED_PARAMS": null,
                "POOL_PARAMS": null,
                "OUTPUT_PARAMS": null,
                "COL_CDN_ID": null,
                "CDN_DYNAMIC_PARAMS": null,
                "CDN_FIXED_PARAMS": null
            },
            {
                "ROW_ID": 3,
                "LNG_ID": "en",
                "TBL_ID": 1,
                "COL_ID": 4,
                "COL_SEQ": 4,
                "COL_DD_ID": "USR_NAME",
                "COL_LABEL": "User Name",
                "COL_TARGET": "USR_NAME",
                "COL_TYPE": "text",
                "COL_RULES": null,
                "COL_RULES_VALUES": null,
                "COL_DEFAULT": null,
                "COL_VISIBLE": "Y",
                "COL_DISABLED": "N",
                "COL_REQUIRED": "N",
                "COL_KEY": "N",
                "COL_FILTER": "N",
                "DYNAMIC_PARAMS": null,
                "FIXED_PARAMS": null,
                "POOL_PARAMS": null,
                "OUTPUT_PARAMS": null,
                "COL_CDN_ID": null,
                "CDN_DYNAMIC_PARAMS": null,
                "CDN_FIXED_PARAMS": null
            },
            {
                "ROW_ID": 4,
                "LNG_ID": "en",
                "TBL_ID": 1,
                "COL_ID": 5,
                "COL_SEQ": 5,
                "COL_DD_ID": "USR_STATUS",
                "COL_LABEL": "Status",
                "COL_TARGET": "USR_STATUS",
                "COL_TYPE": "boolean",
                "COL_RULES": "BOOLEAN",
                "COL_RULES_VALUES": "01",
                "COL_DEFAULT": null,
                "COL_VISIBLE": "Y",
                "COL_DISABLED": "N",
                "COL_REQUIRED": "N",
                "COL_KEY": "N",
                "COL_FILTER": "N",
                "DYNAMIC_PARAMS": null,
                "FIXED_PARAMS": null,
                "POOL_PARAMS": null,
                "OUTPUT_PARAMS": null,
                "COL_CDN_ID": null,
                "CDN_DYNAMIC_PARAMS": null,
                "CDN_FIXED_PARAMS": null
            },
            {
                "ROW_ID": 5,
                "LNG_ID": "en",
                "TBL_ID": 1,
                "COL_ID": 6,
                "COL_SEQ": 6,
                "COL_DD_ID": "USR_DT_CREATION",
                "COL_LABEL": "Creation Date",
                "COL_TARGET": "USR_DT_CREATION",
                "COL_TYPE": "date",
                "COL_RULES": null,
                "COL_RULES_VALUES": null,
                "COL_DEFAULT": null,
                "COL_VISIBLE": "Y",
                "COL_DISABLED": "N",
                "COL_REQUIRED": "N",
                "COL_KEY": "N",
                "COL_FILTER": "N",
                "DYNAMIC_PARAMS": null,
                "FIXED_PARAMS": null,
                "POOL_PARAMS": null,
                "OUTPUT_PARAMS": null,
                "COL_CDN_ID": null,
                "CDN_DYNAMIC_PARAMS": null,
                "CDN_FIXED_PARAMS": null
            },
            {
                "ROW_ID": 6,
                "LNG_ID": "en",
                "TBL_ID": 1,
                "COL_ID": 7,
                "COL_SEQ": 7,
                "COL_DD_ID": "USR_DT_LOGIN",
                "COL_LABEL": "Login Date",
                "COL_TARGET": "USR_DT_LOGIN",
                "COL_TYPE": "date",
                "COL_RULES": null,
                "COL_RULES_VALUES": null,
                "COL_DEFAULT": null,
                "COL_VISIBLE": "Y",
                "COL_DISABLED": "N",
                "COL_REQUIRED": "N",
                "COL_KEY": "N",
                "COL_FILTER": "N",
                "DYNAMIC_PARAMS": null,
                "FIXED_PARAMS": null,
                "POOL_PARAMS": null,
                "OUTPUT_PARAMS": null,
                "COL_CDN_ID": null,
                "CDN_DYNAMIC_PARAMS": null,
                "CDN_FIXED_PARAMS": null
            },
            {
                "ROW_ID": 7,
                "LNG_ID": "en",
                "TBL_ID": 1,
                "COL_ID": 14,
                "COL_SEQ": 8,
                "COL_DD_ID": "LAST_USAGE",
                "COL_LABEL": "Last Usage",
                "COL_TARGET": "LAST_USAGE",
                "COL_TYPE": "date",
                "COL_RULES": null,
                "COL_RULES_VALUES": null,
                "COL_DEFAULT": null,
                "COL_VISIBLE": "Y",
                "COL_DISABLED": "N",
                "COL_REQUIRED": "N",
                "COL_KEY": "N",
                "COL_FILTER": "N",
                "DYNAMIC_PARAMS": null,
                "FIXED_PARAMS": null,
                "POOL_PARAMS": null,
                "OUTPUT_PARAMS": null,
                "COL_CDN_ID": null,
                "CDN_DYNAMIC_PARAMS": null,
                "CDN_FIXED_PARAMS": null
            },
            {
                "ROW_ID": 8,
                "LNG_ID": "en",
                "TBL_ID": 1,
                "COL_ID": 8,
                "COL_SEQ": 9,
                "COL_DD_ID": "USRP_TECHNICAL",
                "COL_LABEL": "Technical (Y/N)",
                "COL_TARGET": "USRP_TECHNICAL",
                "COL_TYPE": "boolean",
                "COL_RULES": "BOOLEAN",
                "COL_RULES_VALUES": "Y",
                "COL_DEFAULT": null,
                "COL_VISIBLE": "Y",
                "COL_DISABLED": "N",
                "COL_REQUIRED": "N",
                "COL_KEY": "N",
                "COL_FILTER": "N",
                "DYNAMIC_PARAMS": null,
                "FIXED_PARAMS": null,
                "POOL_PARAMS": null,
                "OUTPUT_PARAMS": null,
                "COL_CDN_ID": null,
                "CDN_DYNAMIC_PARAMS": null,
                "CDN_FIXED_PARAMS": null
            },
            {
                "ROW_ID": 9,
                "LNG_ID": "en",
                "TBL_ID": 1,
                "COL_ID": 9,
                "COL_SEQ": 10,
                "COL_DD_ID": "USRP_GENERIC",
                "COL_LABEL": "Generic (Y/N)",
                "COL_TARGET": "USRP_GENERIC",
                "COL_TYPE": "boolean",
                "COL_RULES": "BOOLEAN",
                "COL_RULES_VALUES": "Y",
                "COL_DEFAULT": null,
                "COL_VISIBLE": "Y",
                "COL_DISABLED": "N",
                "COL_REQUIRED": "N",
                "COL_KEY": "N",
                "COL_FILTER": "N",
                "DYNAMIC_PARAMS": null,
                "FIXED_PARAMS": null,
                "POOL_PARAMS": null,
                "OUTPUT_PARAMS": null,
                "COL_CDN_ID": null,
                "CDN_DYNAMIC_PARAMS": null,
                "CDN_FIXED_PARAMS": null
            },
            {
                "ROW_ID": 10,
                "LNG_ID": "en",
                "TBL_ID": 1,
                "COL_ID": 10,
                "COL_SEQ": 11,
                "COL_DD_ID": "USRP_ID_LINKED",
                "COL_LABEL": "Linked User ID",
                "COL_TARGET": "USRP_ID_LINKED",
                "COL_TYPE": "text",
                "COL_RULES": null,
                "COL_RULES_VALUES": null,
                "COL_DEFAULT": null,
                "COL_VISIBLE": "N",
                "COL_DISABLED": "N",
                "COL_REQUIRED": "N",
                "COL_KEY": "N",
                "COL_FILTER": "N",
                "DYNAMIC_PARAMS": null,
                "FIXED_PARAMS": null,
                "POOL_PARAMS": null,
                "OUTPUT_PARAMS": null,
                "COL_CDN_ID": null,
                "CDN_DYNAMIC_PARAMS": null,
                "CDN_FIXED_PARAMS": null
            },
            {
                "ROW_ID": 11,
                "LNG_ID": "en",
                "TBL_ID": 1,
                "COL_ID": 11,
                "COL_SEQ": 12,
                "COL_DD_ID": "USR_REGISTRATION",
                "COL_LABEL": "Registration",
                "COL_TARGET": "USR_REGISTRATION",
                "COL_TYPE": "text",
                "COL_RULES": null,
                "COL_RULES_VALUES": null,
                "COL_DEFAULT": null,
                "COL_VISIBLE": "N",
                "COL_DISABLED": "N",
                "COL_REQUIRED": "N",
                "COL_KEY": "N",
                "COL_FILTER": "N",
                "DYNAMIC_PARAMS": null,
                "FIXED_PARAMS": null,
                "POOL_PARAMS": null,
                "OUTPUT_PARAMS": null,
                "COL_CDN_ID": null,
                "CDN_DYNAMIC_PARAMS": null,
                "CDN_FIXED_PARAMS": null
            },
            {
                "ROW_ID": 12,
                "LNG_ID": "en",
                "TBL_ID": 1,
                "COL_ID": 12,
                "COL_SEQ": 13,
                "COL_DD_ID": "USR_DT_REFRESH",
                "COL_LABEL": "Refresh Date",
                "COL_TARGET": "USR_DT_REFRESH",
                "COL_TYPE": "date",
                "COL_RULES": null,
                "COL_RULES_VALUES": null,
                "COL_DEFAULT": null,
                "COL_VISIBLE": "N",
                "COL_DISABLED": "N",
                "COL_REQUIRED": "N",
                "COL_KEY": "N",
                "COL_FILTER": "N",
                "DYNAMIC_PARAMS": null,
                "FIXED_PARAMS": null,
                "POOL_PARAMS": null,
                "OUTPUT_PARAMS": null,
                "COL_CDN_ID": null,
                "CDN_DYNAMIC_PARAMS": null,
                "CDN_FIXED_PARAMS": null
            },
            {
                "ROW_ID": 13,
                "LNG_ID": "en",
                "TBL_ID": 1,
                "COL_ID": 13,
                "COL_SEQ": 14,
                "COL_DD_ID": "USR_UKID",
                "COL_LABEL": "UKID",
                "COL_TARGET": "USR_UKID",
                "COL_TYPE": "number",
                "COL_RULES": null,
                "COL_RULES_VALUES": null,
                "COL_DEFAULT": null,
                "COL_VISIBLE": "N",
                "COL_DISABLED": "N",
                "COL_REQUIRED": "N",
                "COL_KEY": "N",
                "COL_FILTER": "N",
                "DYNAMIC_PARAMS": null,
                "FIXED_PARAMS": null,
                "POOL_PARAMS": null,
                "OUTPUT_PARAMS": null,
                "COL_CDN_ID": null,
                "CDN_DYNAMIC_PARAMS": null,
                "CDN_FIXED_PARAMS": null
            }
        ],
        "status": "success",
        "hasMore": false,
        "limit": 1000,
        "offset": 0,
        "count": 13
    },
    "columns": [
        {
            "header": "Application ID",
            "field": "APPS_ID",
            "type": "number",
            "operator": "=",
            "rules": "LOOKUP",
            "key": true,
            "disabled": false,
            "required": true,
            "rulesValues": "1",
            "default": null,
            "target": "USR_APPS_ID",
            "editable": true,
            "visible": true,
            "filter": false,
            "dynamic_params": null,
            "fixed_params": null,
            "pool_params": null,
            "output_params": null,
            "col_cdn_id": null,
            "accessorKey": "USR_APPS_ID"
        },
        {
            "header": "User ID",
            "field": "USR_ID",
            "type": "text",
            "operator": "like",
            "rules": "DISABLED",
            "key": true,
            "disabled": false,
            "required": true,
            "rulesValues": "6",
            "default": null,
            "target": "USR_ID",
            "editable": true,
            "visible": true,
            "filter": true,
            "dynamic_params": null,
            "fixed_params": null,
            "pool_params": null,
            "output_params": null,
            "col_cdn_id": null,
            "accessorKey": "USR_ID"
        },
        {
            "header": "User Name",
            "field": "USR_NAME",
            "type": "text",
            "operator": "like",
            "rules": null,
            "key": false,
            "disabled": false,
            "required": false,
            "rulesValues": null,
            "default": null,
            "target": "USR_NAME",
            "editable": true,
            "visible": true,
            "filter": false,
            "dynamic_params": null,
            "fixed_params": null,
            "pool_params": null,
            "output_params": null,
            "col_cdn_id": null,
            "accessorKey": "USR_NAME"
        },
        {
            "header": "Status",
            "field": "USR_STATUS",
            "type": "boolean",
            "operator": "=",
            "rules": "BOOLEAN",
            "key": false,
            "disabled": false,
            "required": false,
            "rulesValues": "01",
            "default": null,
            "target": "USR_STATUS",
            "editable": true,
            "visible": true,
            "filter": false,
            "dynamic_params": null,
            "fixed_params": null,
            "pool_params": null,
            "output_params": null,
            "col_cdn_id": null,
            "accessorKey": "USR_STATUS"
        },
        {
            "header": "Creation Date",
            "field": "USR_DT_CREATION",
            "type": "date",
            "operator": "=",
            "rules": null,
            "key": false,
            "disabled": false,
            "required": false,
            "rulesValues": null,
            "default": null,
            "target": "USR_DT_CREATION",
            "editable": true,
            "visible": true,
            "filter": false,
            "dynamic_params": null,
            "fixed_params": null,
            "pool_params": null,
            "output_params": null,
            "col_cdn_id": null,
            "accessorKey": "USR_DT_CREATION"
        },
        {
            "header": "Login Date",
            "field": "USR_DT_LOGIN",
            "type": "date",
            "operator": "=",
            "rules": null,
            "key": false,
            "disabled": false,
            "required": false,
            "rulesValues": null,
            "default": null,
            "target": "USR_DT_LOGIN",
            "editable": true,
            "visible": true,
            "filter": false,
            "dynamic_params": null,
            "fixed_params": null,
            "pool_params": null,
            "output_params": null,
            "col_cdn_id": null,
            "accessorKey": "USR_DT_LOGIN"
        },
        {
            "header": "Last Usage",
            "field": "LAST_USAGE",
            "type": "date",
            "operator": "=",
            "rules": null,
            "key": false,
            "disabled": false,
            "required": false,
            "rulesValues": null,
            "default": null,
            "target": "LAST_USAGE",
            "editable": true,
            "visible": true,
            "filter": false,
            "dynamic_params": null,
            "fixed_params": null,
            "pool_params": null,
            "output_params": null,
            "col_cdn_id": null,
            "accessorKey": "LAST_USAGE"
        },
        {
            "header": "Technical (Y/N)",
            "field": "USRP_TECHNICAL",
            "type": "boolean",
            "operator": "=",
            "rules": "BOOLEAN",
            "key": false,
            "disabled": false,
            "required": false,
            "rulesValues": "Y",
            "default": null,
            "target": "USRP_TECHNICAL",
            "editable": true,
            "visible": true,
            "filter": false,
            "dynamic_params": null,
            "fixed_params": null,
            "pool_params": null,
            "output_params": null,
            "col_cdn_id": null,
            "accessorKey": "USRP_TECHNICAL"
        },
        {
            "header": "Generic (Y/N)",
            "field": "USRP_GENERIC",
            "type": "boolean",
            "operator": "=",
            "rules": "BOOLEAN",
            "key": false,
            "disabled": false,
            "required": false,
            "rulesValues": "Y",
            "default": null,
            "target": "USRP_GENERIC",
            "editable": true,
            "visible": true,
            "filter": false,
            "dynamic_params": null,
            "fixed_params": null,
            "pool_params": null,
            "output_params": null,
            "col_cdn_id": null,
            "accessorKey": "USRP_GENERIC"
        },
        {
            "header": "Linked User ID",
            "field": "USRP_ID_LINKED",
            "type": "text",
            "operator": "like",
            "rules": null,
            "key": false,
            "disabled": false,
            "required": false,
            "rulesValues": null,
            "default": null,
            "target": "USRP_ID_LINKED",
            "editable": true,
            "visible": false,
            "filter": false,
            "dynamic_params": null,
            "fixed_params": null,
            "pool_params": null,
            "output_params": null,
            "col_cdn_id": null,
            "accessorKey": "USRP_ID_LINKED"
        },
        {
            "header": "Registration",
            "field": "USR_REGISTRATION",
            "type": "text",
            "operator": "like",
            "rules": null,
            "key": false,
            "disabled": false,
            "required": false,
            "rulesValues": null,
            "default": null,
            "target": "USR_REGISTRATION",
            "editable": true,
            "visible": false,
            "filter": false,
            "dynamic_params": null,
            "fixed_params": null,
            "pool_params": null,
            "output_params": null,
            "col_cdn_id": null,
            "accessorKey": "USR_REGISTRATION"
        },
        {
            "header": "Refresh Date",
            "field": "USR_DT_REFRESH",
            "type": "date",
            "operator": "=",
            "rules": null,
            "key": false,
            "disabled": false,
            "required": false,
            "rulesValues": null,
            "default": null,
            "target": "USR_DT_REFRESH",
            "editable": true,
            "visible": false,
            "filter": false,
            "dynamic_params": null,
            "fixed_params": null,
            "pool_params": null,
            "output_params": null,
            "col_cdn_id": null,
            "accessorKey": "USR_DT_REFRESH"
        },
        {
            "header": "UKID",
            "field": "USR_UKID",
            "type": "number",
            "operator": "=",
            "rules": null,
            "key": false,
            "disabled": false,
            "required": false,
            "rulesValues": null,
            "default": null,
            "target": "USR_UKID",
            "editable": true,
            "visible": false,
            "filter": false,
            "dynamic_params": null,
            "fixed_params": null,
            "pool_params": null,
            "output_params": null,
            "col_cdn_id": null,
            "accessorKey": "USR_UKID"
        }
    ]
}

export const tableData = [
    {
        "ROW_ID": "1",
        "USR_APPS_ID": 10,
        "USR_APPS_ID_LABEL": "JDE_TEMPLATE",
        "USR_ID": "APPLEAD",
        "USR_NAME": "Financial/Distribution Company",
        "USR_STATUS": "N",
        "USR_DT_CREATION": null,
        "USR_DT_LOGIN": null,
        "USRP_TECHNICAL": null,
        "USRP_GENERIC": null,
        "USRP_ID_LINKED": null,
        "USR_REGISTRATION": "430788490",
        "USR_DT_REFRESH": "2025-02-21",
        "USR_UKID": 1,
        "LAST_USAGE": null
    },
    {
        "ROW_ID": "2",
        "USR_APPS_ID": 10,
        "USR_APPS_ID_LABEL": "JDE_TEMPLATE",
        "USR_ID": "CRPCTL",
        "USR_NAME": null,
        "USR_STATUS": "N",
        "USR_DT_CREATION": null,
        "USR_DT_LOGIN": null,
        "USRP_TECHNICAL": null,
        "USRP_GENERIC": null,
        "USRP_ID_LINKED": null,
        "USR_REGISTRATION": null,
        "USR_DT_REFRESH": "2025-02-21",
        "USR_UKID": 1,
        "LAST_USAGE": null
    },
    {
        "ROW_ID": "3",
        "USR_APPS_ID": 10,
        "USR_APPS_ID_LABEL": "JDE_TEMPLATE",
        "USR_ID": "CRPDTA",
        "USR_NAME": null,
        "USR_STATUS": "N",
        "USR_DT_CREATION": null,
        "USR_DT_LOGIN": null,
        "USRP_TECHNICAL": null,
        "USRP_GENERIC": null,
        "USRP_ID_LINKED": null,
        "USR_REGISTRATION": null,
        "USR_DT_REFRESH": "2025-02-21",
        "USR_UKID": 1,
        "LAST_USAGE": null
    },
    {
        "ROW_ID": "4",
        "USR_APPS_ID": 10,
        "USR_APPS_ID_LABEL": "JDE_TEMPLATE",
        "USR_ID": "DD920",
        "USR_NAME": null,
        "USR_STATUS": "N",
        "USR_DT_CREATION": null,
        "USR_DT_LOGIN": null,
        "USRP_TECHNICAL": null,
        "USRP_GENERIC": null,
        "USRP_ID_LINKED": null,
        "USR_REGISTRATION": null,
        "USR_DT_REFRESH": "2025-02-21",
        "USR_UKID": 1,
        "LAST_USAGE": null
    },
    {
        "ROW_ID": "5",
        "USR_APPS_ID": 10,
        "USR_APPS_ID_LABEL": "JDE_TEMPLATE",
        "USR_ID": "DEMO",
        "USR_NAME": "Financial/Distribution Company",
        "USR_STATUS": "01",
        "USR_DT_CREATION": "2024-11-26",
        "USR_DT_LOGIN": null,
        "USRP_TECHNICAL": null,
        "USRP_GENERIC": null,
        "USRP_ID_LINKED": null,
        "USR_REGISTRATION": "430788490",
        "USR_DT_REFRESH": "2025-02-21",
        "USR_UKID": 1,
        "LAST_USAGE": null
    },
    {
        "ROW_ID": "6",
        "USR_APPS_ID": 10,
        "USR_APPS_ID_LABEL": "JDE_TEMPLATE",
        "USR_ID": "DEVUSER",
        "USR_NAME": "Financial/Distribution Company",
        "USR_STATUS": "N",
        "USR_DT_CREATION": null,
        "USR_DT_LOGIN": null,
        "USRP_TECHNICAL": null,
        "USRP_GENERIC": null,
        "USRP_ID_LINKED": null,
        "USR_REGISTRATION": "430788490",
        "USR_DT_REFRESH": "2025-02-21",
        "USR_UKID": 1,
        "LAST_USAGE": null
    },
    {
        "ROW_ID": "7",
        "USR_APPS_ID": 10,
        "USR_APPS_ID_LABEL": "JDE_TEMPLATE",
        "USR_ID": "DV920",
        "USR_NAME": null,
        "USR_STATUS": "N",
        "USR_DT_CREATION": null,
        "USR_DT_LOGIN": null,
        "USRP_TECHNICAL": null,
        "USRP_GENERIC": null,
        "USRP_ID_LINKED": null,
        "USR_REGISTRATION": null,
        "USR_DT_REFRESH": "2025-02-21",
        "USR_UKID": 1,
        "LAST_USAGE": null
    },
    {
        "ROW_ID": "8",
        "USR_APPS_ID": 10,
        "USR_APPS_ID_LABEL": "JDE_TEMPLATE",
        "USR_ID": "JDE",
        "USR_NAME": "Financial/Distribution Company",
        "USR_STATUS": "01",
        "USR_DT_CREATION": null,
        "USR_DT_LOGIN": null,
        "USRP_TECHNICAL": null,
        "USRP_GENERIC": null,
        "USRP_ID_LINKED": null,
        "USR_REGISTRATION": "430788490",
        "USR_DT_REFRESH": "2025-02-21",
        "USR_UKID": 1,
        "LAST_USAGE": null
    },
    {
        "ROW_ID": "9",
        "USR_APPS_ID": 10,
        "USR_APPS_ID_LABEL": "JDE_TEMPLATE",
        "USR_ID": "OL920",
        "USR_NAME": null,
        "USR_STATUS": "N",
        "USR_DT_CREATION": null,
        "USR_DT_LOGIN": null,
        "USRP_TECHNICAL": null,
        "USRP_GENERIC": null,
        "USRP_ID_LINKED": null,
        "USR_REGISTRATION": null,
        "USR_DT_REFRESH": "2025-02-21",
        "USR_UKID": 1,
        "LAST_USAGE": null
    },
    {
        "ROW_ID": "10",
        "USR_APPS_ID": 10,
        "USR_APPS_ID_LABEL": "JDE_TEMPLATE",
        "USR_ID": "PD920",
        "USR_NAME": null,
        "USR_STATUS": "N",
        "USR_DT_CREATION": null,
        "USR_DT_LOGIN": null,
        "USRP_TECHNICAL": null,
        "USRP_GENERIC": null,
        "USRP_ID_LINKED": null,
        "USR_REGISTRATION": null,
        "USR_DT_REFRESH": "2025-02-21",
        "USR_UKID": 1,
        "LAST_USAGE": null
    },
    {
        "ROW_ID": "11",
        "USR_APPS_ID": 10,
        "USR_APPS_ID_LABEL": "JDE_TEMPLATE",
        "USR_ID": "PRODCTL",
        "USR_NAME": null,
        "USR_STATUS": "N",
        "USR_DT_CREATION": null,
        "USR_DT_LOGIN": null,
        "USRP_TECHNICAL": null,
        "USRP_GENERIC": null,
        "USRP_ID_LINKED": null,
        "USR_REGISTRATION": null,
        "USR_DT_REFRESH": "2025-02-21",
        "USR_UKID": 1,
        "LAST_USAGE": null
    },
    {
        "ROW_ID": "12",
        "USR_APPS_ID": 10,
        "USR_APPS_ID_LABEL": "JDE_TEMPLATE",
        "USR_ID": "PRODDTA",
        "USR_NAME": null,
        "USR_STATUS": "N",
        "USR_DT_CREATION": null,
        "USR_DT_LOGIN": null,
        "USRP_TECHNICAL": null,
        "USRP_GENERIC": null,
        "USRP_ID_LINKED": null,
        "USR_REGISTRATION": null,
        "USR_DT_REFRESH": "2025-02-21",
        "USR_UKID": 1,
        "LAST_USAGE": null
    },
    {
        "ROW_ID": "13",
        "USR_APPS_ID": 10,
        "USR_APPS_ID_LABEL": "JDE_TEMPLATE",
        "USR_ID": "PRODUSER",
        "USR_NAME": "Financial/Distribution Company",
        "USR_STATUS": "N",
        "USR_DT_CREATION": null,
        "USR_DT_LOGIN": null,
        "USRP_TECHNICAL": null,
        "USRP_GENERIC": null,
        "USRP_ID_LINKED": null,
        "USR_REGISTRATION": "430788490",
        "USR_DT_REFRESH": "2025-02-21",
        "USR_UKID": 1,
        "LAST_USAGE": null
    },
    {
        "ROW_ID": "14",
        "USR_APPS_ID": 10,
        "USR_APPS_ID_LABEL": "JDE_TEMPLATE",
        "USR_ID": "PS920",
        "USR_NAME": null,
        "USR_STATUS": "N",
        "USR_DT_CREATION": null,
        "USR_DT_LOGIN": null,
        "USRP_TECHNICAL": null,
        "USRP_GENERIC": null,
        "USRP_ID_LINKED": null,
        "USR_REGISTRATION": null,
        "USR_DT_REFRESH": "2025-02-21",
        "USR_UKID": 1,
        "LAST_USAGE": null
    },
    {
        "ROW_ID": "15",
        "USR_APPS_ID": 10,
        "USR_APPS_ID_LABEL": "JDE_TEMPLATE",
        "USR_ID": "PS920CTL",
        "USR_NAME": null,
        "USR_STATUS": "N",
        "USR_DT_CREATION": null,
        "USR_DT_LOGIN": null,
        "USRP_TECHNICAL": null,
        "USRP_GENERIC": null,
        "USRP_ID_LINKED": null,
        "USR_REGISTRATION": null,
        "USR_DT_REFRESH": "2025-02-21",
        "USR_UKID": 1,
        "LAST_USAGE": null
    },
    {
        "ROW_ID": "16",
        "USR_APPS_ID": 10,
        "USR_APPS_ID_LABEL": "JDE_TEMPLATE",
        "USR_ID": "PS920DTA",
        "USR_NAME": null,
        "USR_STATUS": "N",
        "USR_DT_CREATION": null,
        "USR_DT_LOGIN": null,
        "USRP_TECHNICAL": null,
        "USRP_GENERIC": null,
        "USRP_ID_LINKED": null,
        "USR_REGISTRATION": null,
        "USR_DT_REFRESH": "2025-02-21",
        "USR_UKID": 1,
        "LAST_USAGE": null
    },
    {
        "ROW_ID": "17",
        "USR_APPS_ID": 10,
        "USR_APPS_ID_LABEL": "JDE_TEMPLATE",
        "USR_ID": "PY920",
        "USR_NAME": null,
        "USR_STATUS": "N",
        "USR_DT_CREATION": null,
        "USR_DT_LOGIN": null,
        "USRP_TECHNICAL": null,
        "USRP_GENERIC": null,
        "USRP_ID_LINKED": null,
        "USR_REGISTRATION": null,
        "USR_DT_REFRESH": "2025-02-21",
        "USR_UKID": 1,
        "LAST_USAGE": null
    },
    {
        "ROW_ID": "18",
        "USR_APPS_ID": 10,
        "USR_APPS_ID_LABEL": "JDE_TEMPLATE",
        "USR_ID": "SVM920",
        "USR_NAME": null,
        "USR_STATUS": "N",
        "USR_DT_CREATION": null,
        "USR_DT_LOGIN": null,
        "USRP_TECHNICAL": null,
        "USRP_GENERIC": null,
        "USRP_ID_LINKED": null,
        "USR_REGISTRATION": null,
        "USR_DT_REFRESH": "2025-02-21",
        "USR_UKID": 1,
        "LAST_USAGE": null
    },
    {
        "ROW_ID": "19",
        "USR_APPS_ID": 10,
        "USR_APPS_ID_LABEL": "JDE_TEMPLATE",
        "USR_ID": "SY920",
        "USR_NAME": null,
        "USR_STATUS": "N",
        "USR_DT_CREATION": null,
        "USR_DT_LOGIN": null,
        "USRP_TECHNICAL": null,
        "USRP_GENERIC": null,
        "USRP_ID_LINKED": null,
        "USR_REGISTRATION": null,
        "USR_DT_REFRESH": "2025-02-21",
        "USR_UKID": 1,
        "LAST_USAGE": null
    },
    {
        "ROW_ID": "20",
        "USR_APPS_ID": 10,
        "USR_APPS_ID_LABEL": "JDE_TEMPLATE",
        "USR_ID": "TESTCTL",
        "USR_NAME": null,
        "USR_STATUS": "N",
        "USR_DT_CREATION": null,
        "USR_DT_LOGIN": null,
        "USRP_TECHNICAL": null,
        "USRP_GENERIC": null,
        "USRP_ID_LINKED": null,
        "USR_REGISTRATION": null,
        "USR_DT_REFRESH": "2025-02-21",
        "USR_UKID": 1,
        "LAST_USAGE": null
    },
    {
        "ROW_ID": "21",
        "USR_APPS_ID": 10,
        "USR_APPS_ID_LABEL": "JDE_TEMPLATE",
        "USR_ID": "TESTDTA",
        "USR_NAME": null,
        "USR_STATUS": "N",
        "USR_DT_CREATION": null,
        "USR_DT_LOGIN": null,
        "USRP_TECHNICAL": null,
        "USRP_GENERIC": null,
        "USRP_ID_LINKED": null,
        "USR_REGISTRATION": null,
        "USR_DT_REFRESH": "2025-02-21",
        "USR_UKID": 1,
        "LAST_USAGE": null
    }
]

export async function getTableProperties() {
    return tableProperties
  }
  
  export async function getTableData() {
    return tableData
  }
